#g++ main.cpp -g -O0 -std=c++11 -Wall -o main -static
CC=g++
SRC=main.cpp
CFLAGS=-g -O0 -std=c++11 -Wall
OUT=main
FLAGS=-static

all:
	$(CC) $(SRC) $(CFLAGS) -o $(OUT) $(FLAGS)

clean:
	rm -rf $(OUT)
